-- ════════════════════════════════════════════════════════════════════════════
--  ⛔ INVALID AS WRITTEN — DO NOT RUN.
-- ════════════════════════════════════════════════════════════════════════════
--
-- This file proposed a unique index on transactions.reference. That constraint
-- is wrong for this database: recurring transactions INTENTIONALLY share one
-- reference across every row of the series. Every statement below is commented
-- out so pasting the whole file into the SQL editor does nothing. It is kept,
-- not deleted, so the reasoning survives for whoever finds it next.
--
-- Written 2026-09-13. Marked invalid 2026-09-14.
--
-- ── WHY IT IS INVALID ───────────────────────────────────────────────────────
--
--   The production app (northernstar-app, public/index.html, saveTx) turns a
--   transaction marked "recurring" into a series: the first row, then one row
--   per future month / fortnight / week. Every row in the series is inserted
--   with the SAME `reference` — that shared reference is what ties the series
--   together. It is by design, not a collision.
--
--   With this index in place:
--
--   1. Every recurring add breaks, not just racing ones. The first row inserts;
--      the batch insert of the rest of the series then fails with 23505. And
--      saveTx ignores that second error (`if(!r2.error && r2.data)`), so the
--      operator sees "Saved + N recurring entries" while none of those N rows
--      were written. A silent partial write — worse than the duplicate problem
--      the index was meant to fix.
--
--   2. STEP 1 (the duplicate finder) would list every recurring series as a
--      "duplicate" and told the reader to renumber them by hand before STEP 2.
--      Following that instruction would break the series apart in live data.
--
--   The premise was "one transaction per reference". The real model is "one
--   reference per transaction OR per recurring series" — a plain unique index
--   cannot express that.
--
--   Why it LOOKS safe (and isn't): checked against live data on 2026-09-14, no
--   reference is currently shared by two rows, and the index had never been
--   created. So STEP 1 returns nothing and STEP 2 succeeds today. The damage
--   only shows up afterwards, the next time anyone adds a recurring
--   transaction. An empty STEP 1 is not evidence the constraint is right.
--
-- ── WHAT FROM THE ORIGINAL REASONING STILL HOLDS ────────────────────────────
--
--   * The count+1 reuse bug was real: getNextRef() returned COUNT(rows with the
--     prefix) + 1, so deleting any transaction made the next reference reuse a
--     live one. FIXED in northernstar-app on 2026-09-14 — getNextRef now uses
--     MAX(suffix) + 1 (nextRefFor), the same rule as nextSequence() here in
--     src/lib/data/references.ts.
--
--   * The concurrent race is NOT closed. Two people adding a transaction at the
--     same moment can still compute the same reference. Nothing in the database
--     arbitrates that today.
--
--   * src/lib/data/reference-allocator.ts still describes this index as half of
--     the fix and retries on 23505. That retry never fires without the index.
--     Its doc comment needs updating to match this file.
--
-- ── IF SOMEONE REVISITS THIS ────────────────────────────────────────────────
--
--   Any uniqueness rule has to allow a recurring series first. Options to
--   evaluate — none tested, none endorsed yet:
--     - an explicit series id column, with uniqueness on
--       (reference) for non-series rows and (reference, date) within a series;
--     - allocating references from a database sequence/function so the race
--       disappears without a constraint on existing rows.
--   Whatever is chosen, check it against saveTx's recurring path AND fix that
--   path's swallowed r2.error before relying on the database to reject rows.
--
-- ════════════════════════════════════════════════════════════════════════════
--  ORIGINAL SQL — kept for the record, all commented out. Do not uncomment.
-- ════════════════════════════════════════════════════════════════════════════
--
-- ── (original) STEP 1: find existing duplicates ─────────────────────────────
-- NOTE: a recurring series legitimately shows up here as a "duplicate". Never
-- renumber rows because this query returned them.
--
-- select
--   reference,
--   count(*)                              as row_count,
--   array_agg(id order by date, id)       as transaction_ids,
--   array_agg(date order by date, id)     as dates,
--   array_agg(description order by date, id) as descriptions
-- from public.transactions
-- where reference is not null
--   and btrim(reference) <> ''
-- group by reference
-- having count(*) > 1
-- order by count(*) desc, reference;
--
-- Still useful on its own (read-only): the highest sequence in use per prefix,
-- which is what both apps' next-reference logic now derives from.
--
-- select split_part(reference,'-',1) as prefix,
--        max(nullif(split_part(reference,'-',2),'')::int) as highest,
--        count(*) as used
--   from public.transactions
--  where reference ~ '^[A-Z0-9]+-\d+$'
--  group by 1 order by 1;
--
-- ── (original) STEP 2: enforce it — INVALID, see above ──────────────────────
--
-- create unique index if not exists transactions_reference_unique
--   on public.transactions (reference)
--   where reference is not null and btrim(reference) <> '';
--
-- comment on index public.transactions_reference_unique is
--   'One transaction per reference. ...';
--
-- ── (original) ROLLBACK ─────────────────────────────────────────────────────
-- If this was ever run anyway, undo it — dropping the index is safe and instant:
--
-- drop index if exists public.transactions_reference_unique;
